// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Timeframe } from "./Timeframe";

export type BacktestRequest = { name: string, exchange: string, symbol: string, timeframe: Timeframe, };
