// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileNodeType } from "./FileNodeType";

export type FileNode = { name: string, path: string, type: FileNodeType, };
