// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileNode } from "./FileNode";

export type GetSourceResponse = { "type": "file", name: string, path: string, content: string, } | { "type": "directory", name: string, path: string, children: Array<FileNode>, };
